version: "3.12"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "bot_db"
      POSTGRES_USER: "adminuser"
      POSTGRES_PASSWORD: "adminpasswrd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../init_database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  bot:
    build:
      dockerfile: Dockerfile

